import { RemovalPolicy, Stack, type StackProps } from "aws-cdk-lib";
import * as secretsmanager from "aws-cdk-lib/aws-secretsmanager";
import type { Construct } from "constructs";
import type { EnvironmentConfig } from "./config.ts";

export interface SecretsStackProps extends StackProps {
  config: EnvironmentConfig;
}

/**
 * Every runtime secret lives here. Placeholders are created once by CDK; the real values are
 * written by a human (or by Supabase/Stripe) in the console or with `aws secretsmanager put-secret-value`.
 * Nothing secret is ever passed as a CDK parameter, environment variable or context value.
 */
export class SecretsStack extends Stack {
  readonly appSecret: secretsmanager.Secret;

  constructor(scope: Construct, id: string, props: SecretsStackProps) {
    super(scope, id, props);
    const { config } = props;

    this.appSecret = new secretsmanager.Secret(this, "AppSecret", {
      secretName: `menu-studio/${config.name}/app`,
      description: `Menu Studio ${config.name} runtime secrets. Fields are injected into ECS tasks one by one.`,
      generateSecretString: {
        // PRINT_TOKEN_SECRET is generated by AWS, so no person ever sees or pastes it.
        generateStringKey: "PRINT_TOKEN_SECRET",
        passwordLength: 48,
        excludePunctuation: true,
        secretStringTemplate: JSON.stringify({
          DATABASE_URL: "postgres://REPLACE_ME",
          SUPABASE_URL: "https://REPLACE_ME.supabase.co",
          SUPABASE_ANON_KEY: "REPLACE_ME",
          SUPABASE_SERVICE_ROLE_KEY: "REPLACE_ME",
          ANTHROPIC_API_KEY: "REPLACE_ME",
          STRIPE_SECRET_KEY: "REPLACE_ME",
          STRIPE_WEBHOOK_SECRET: "REPLACE_ME",
          RAZORPAY_KEY_ID: "REPLACE_ME",
          RAZORPAY_KEY_SECRET: "REPLACE_ME",
          RAZORPAY_WEBHOOK_SECRET: "REPLACE_ME",
          SENTRY_DSN_API: "",
          SENTRY_DSN_WORKER: "",
        }),
      },
      removalPolicy: config.name === "production" ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY,
    });
  }
}
