/**
 * Mirrors the curated Google Fonts into packages/design-system/fonts so menus never load
 * fonts from Google's CDN at runtime (privacy for QR visitors, deterministic exports).
 * Keeps Google's unicode-range slices so browsers download only the glyphs in use.
 *
 *   pnpm fonts:mirror
 */
import { createHash } from "node:crypto";
import { mkdir, writeFile, readdir, rm } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { catalogFamilies } from "../src/catalog/fonts.ts";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "fonts");
const filesDir = join(outDir, "files");
// Chrome 60 supports woff2 and unicode-range but predates variable fonts, so the CSS API
// returns static instances. Variable fonts embed in Chromium PDFs as Type3 glyph procedures,
// which print preflight tools reject; static TrueType embeds as proper subset fonts.
const USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36";

function familyQuery(family: string, weights: number[], italic: boolean): string {
  const name = family.replace(/ /g, "+");
  if (!italic) return `family=${name}:wght@${weights.join(";")}`;
  const tuples = [...weights.map((w) => `0,${w}`), ...weights.map((w) => `1,${w}`)];
  return `family=${name}:ital,wght@${tuples.join(";")}`;
}

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, { headers: { "user-agent": USER_AGENT } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res.text();
}

/** Fonts for the owner app's own chrome. Not part of the menu catalog. */
const APP_FAMILIES = [
  { family: "Instrument Serif", weights: [400], italic: true },
  { family: "Geist", weights: [400, 500, 600], italic: false },
];

async function main() {
  await mkdir(filesDir, { recursive: true });
  for (const f of await readdir(filesDir)) await rm(join(filesDir, f));
  let fileCount = 0;
  let bytes = 0;

  for (const [outName, families] of [
    ["fonts.css", catalogFamilies()],
    ["app-fonts.css", APP_FAMILIES],
  ] as const) {
    const cssParts: string[] = [
      "/* Generated by scripts/mirror-fonts.ts. Do not edit. Fonts are licensed under the SIL Open Font License. */",
    ];
    for (const { family, weights, italic } of families) {
      let css = await fetchText(
        `https://fonts.googleapis.com/css2?${familyQuery(family, weights, italic)}&display=swap`,
      );
      const urls = [
        ...new Set(
          [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map(
            (m) => m[1] ?? "",
          ),
        ),
      ].filter(Boolean);
      for (const url of urls) {
        const res = await fetch(url, { headers: { "user-agent": USER_AGENT } });
        if (!res.ok) throw new Error(`${res.status} for ${url}`);
        const buf = Buffer.from(await res.arrayBuffer());
        const name = `${family.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${createHash("sha1").update(url).digest("hex").slice(0, 10)}.woff2`;
        await writeFile(join(filesDir, name), buf);
        css = css.split(url).join(`./files/${name}`);
        fileCount++;
        bytes += buf.length;
      }
      cssParts.push(`/* ${family} */`, css.trim());
      process.stdout.write(`  ${family}: ${urls.length} files\n`);
    }
    await writeFile(join(outDir, outName), `${cssParts.join("\n")}\n`);
  }

  process.stdout.write(
    `Mirrored ${fileCount} files (${(bytes / 1024 / 1024).toFixed(1)} MB) into ${outDir}\n`,
  );
}

await main();
